// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwqFWjDt45O1kJVqRNt2SYt7aZZZsTFI',
    appId: '1:794215675752:web:2819701bf23ff804dfc8dd',
    messagingSenderId: '794215675752',
    projectId: 'crud-eb4cc',
    authDomain: 'crud-eb4cc.firebaseapp.com',
    databaseURL: 'https://crud-eb4cc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-eb4cc.appspot.com',
    measurementId: 'G-99WMJ1STEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCicuyPb2JIZbhgU8fi3hxcNmDQHMF1iGs',
    appId: '1:794215675752:android:5e4adfc6d4e2862bdfc8dd',
    messagingSenderId: '794215675752',
    projectId: 'crud-eb4cc',
    databaseURL: 'https://crud-eb4cc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-eb4cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4e-PSM_3W2cS2R6NdYgB_O5VbtWwAJj0',
    appId: '1:794215675752:ios:357b16191942631ddfc8dd',
    messagingSenderId: '794215675752',
    projectId: 'crud-eb4cc',
    databaseURL: 'https://crud-eb4cc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-eb4cc.appspot.com',
    iosClientId: '794215675752-e0o87i75n8fdcv4u90evkr2o0asg78uv.apps.googleusercontent.com',
    iosBundleId: 'com.socialauth.app',
  );
}
